// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2026 Derek Reynolds

import DHCore
import DeskhopChannel

/*
 * The seal, from this helper's side (#113).
 *
 * What these gate is the one thing the C suite cannot: **CryptoKit's**
 * AES-256-GCM producing the same bytes as everyone else's. The golden vectors
 * were generated by an independent Python implementation, `tests/seal_test.c`
 * reproduces them with the suite's own reference cipher, and these reproduce
 * them again through the cipher this helper actually ships. Three
 * implementations agreeing on the published bytes is what says the payload one
 * Mac seals is a payload the other computer can open.
 *
 * The key material is the same fixed, published, obviously fake material
 * `tools/gen-frame-vectors.py` uses — written as ranges here, the way
 * BindingTests.swift already writes the session material.
 */

let sealTests: [(String, () throws -> Void)] = [
    ("the seal exchange matches the golden vectors", testTheSealExchangeMatchesTheWire),
    ("a sealed payload matches the golden vectors", testASealedPayloadMatchesTheWire),
    ("what this helper seals, the far end opens", testTheRoundTripCarriesTheBytes),
    ("an edited clear head does not open", testAnEditedHeadDoesNotOpen),
    ("nothing goes out unsealed", testNothingGoesOutUnsealed),
    ("SEAL_STALE round-trips and names its seal", testStaleRoundTrips),
]

/* The published material, in the order each call draws it. */
private let sealID: UInt32 = 0x1122_3344
private let sealIDBytes: [UInt8] = [0x44, 0x33, 0x22, 0x11]
private let offerNonce = [UInt8](0x20...0x2F)
private let acceptNonce = [UInt8](0x30...0x3F)
private let offerPrivate = [UInt8](0x41...0x60)
private let acceptPrivate = [UInt8](0x61...0x80)

/*
 * An entropy source that hands back exactly what a scenario needs, in order.
 * A draw of the wrong size returns bytes of that size anyway, so the seal
 * refuses them and the failure lands as a thrown error rather than as silently
 * different key material.
 */
private func scripted(_ draws: [[UInt8]]) -> (Int) -> [UInt8] {
    var remaining = draws
    return { count in
        guard !remaining.isEmpty else { return [UInt8](repeating: 0, count: count) }
        return remaining.removeFirst()
    }
}

private func offeringSeal() -> ClipboardSeal {
    ClipboardSeal(entropy: scripted([sealIDBytes, offerNonce, offerPrivate]))
}

private func acceptingSeal() -> ClipboardSeal {
    ClipboardSeal(entropy: scripted([acceptNonce, acceptPrivate]))
}

/// The body of a golden frame: past the header and the hop's authentication
/// prefix, neither of which belongs to the seal.
private func goldenBody(_ name: String) throws -> [UInt8] {
    let (frame, _) = try FrameCodec.decode(try GoldenVectors.named(name))
    return Array(frame.payload.dropFirst(Int(DH_FRAME_AUTH_PREFIX_SIZE)))
}

func testTheSealExchangeMatchesTheWire() throws {
    let sender = offeringSeal()
    let receiver = acceptingSeal()

    let offer = try sender.offer()
    Check.equal(offer, try goldenBody("seal_offer"), "the SEAL_OFFER body is not the wire's")
    Check.that(!sender.canSeal, "a seal went live before it was accepted")

    let accept = try receiver.accept(offer: offer)
    Check.equal(accept, try goldenBody("seal_accept"), "the SEAL_ACCEPT body is not the wire's")
    Check.equal(receiver.acceptedSealID, sealID, "the accepter named the wrong seal")

    try sender.accepted(accept)
    Check.that(sender.canSeal, "the accept did not produce a key")
}

/*
 * The two messages that carry the user's bytes, sealed by CryptoKit and
 * compared with what Python produced. They come off one key in this order, so
 * the offer spends counter 0 and the chunk counter 1.
 */
func testASealedPayloadMatchesTheWire() throws {
    let sender = offeringSeal()
    let receiver = acceptingSeal()
    try sender.accepted(try receiver.accept(offer: try sender.offer()))

    let offer = try sender.seal(ClipOffer(id: 1, kind: 0, total: 2))
    Check.equal(offer, try goldenBody("clip_offer_text2"), "the sealed CLIP_OFFER is not the wire's")

    let hi: [UInt8] = [0x68, 0x69]
    let chunk = try sender.seal(ClipChunk(id: 2, seq: 0, crc32: 0xD893_2AAC, data: hi))
    Check.equal(chunk, try goldenBody("clip_chunk_hi"), "the sealed CLIP_CHUNK is not the wire's")

    /* And the far end reads what was put in. */
    let readOffer = try receiver.openOffer(offer)
    Check.equal(readOffer, ClipOffer(id: 1, kind: 0, total: 2), "the offer opened to something else")
    let readChunk = try receiver.openChunk(chunk)
    Check.equal(readChunk, ClipChunk(id: 2, seq: 0, crc32: 0xD893_2AAC, data: hi),
                "the chunk opened to something else")
}

/* Fidelity: the bytes delivered are the bytes sealed, at the largest size one
   frame can carry, with metadata alongside. */
func testTheRoundTripCarriesTheBytes() throws {
    let sender = offeringSeal()
    let receiver = acceptingSeal()
    try sender.accepted(try receiver.accept(offer: try sender.offer()))

    let meta = [UInt8]("[{\"name\":\"notes.txt\",\"size\":9}]".utf8)
    let offer = try sender.seal(ClipOffer(id: 9, kind: 2, total: 4032, meta: meta))
    Check.equal(try receiver.openOffer(offer).meta, meta, "the metadata changed")

    let data = (0..<ClipboardSeal.maxChunkData).map { UInt8(($0 &* 7) & 0xFF) }
    let sealed = try sender.seal(ClipChunk(id: 9, seq: 1, crc32: 0x1234_5678, data: data))
    let opened = try receiver.openChunk(sealed)
    Check.equal(opened.data, data, "the bytes changed")
    Check.equal(opened.crc32, 0x1234_5678, "the CRC32 inside the seal changed")

    /* One byte past what a frame can carry is refused, not truncated. */
    Check.throwsSealError(.bufferTooSmall, "an oversized chunk was sealed anyway") {
        try sender.seal(ClipChunk(id: 9, seq: 2, crc32: 0, data: data + [0]))
    }
}

/* The clear head is the AAD, so a board that edited an id, a sequence number
   or a counter in flight would produce a frame that no longer opens. */
func testAnEditedHeadDoesNotOpen() throws {
    let sender = offeringSeal()
    let receiver = acceptingSeal()
    try sender.accepted(try receiver.accept(offer: try sender.offer()))

    let sealed = try sender.seal(ClipChunk(id: 5, seq: 2, crc32: 0, data: [1, 2, 3, 4]))
    for (offset, what) in [(0, "the transfer id"), (4, "the sequence number"),
                           (12, "the seal counter"), (sealed.count - 1, "the tag")] {
        var edited = sealed
        edited[offset] ^= 0x01
        Check.throwsSealError(.notAuthenticated, "an edit to \(what) still opened") {
            try receiver.openChunk(edited)
        }
    }
    Check.doesNotThrowSeal("the unedited frame stopped opening") {
        try receiver.openChunk(sealed)
    }
}

/*
 * There is no unsealed path and no build that turns the seal off: #44's
 * exemption is the board's, and the board is not a party to this key. With no
 * seal there is simply nothing to send.
 */
func testNothingGoesOutUnsealed() throws {
    let sender = offeringSeal()
    Check.that(!sender.canSeal, "a fresh helper claims it can seal")
    Check.throwsSealError(.noSeal, "a chunk went out with no seal") {
        try sender.seal(ClipChunk(id: 1, seq: 0, crc32: 0, data: [1, 2, 3, 4]))
    }
    Check.throwsSealError(.noSeal, "an offer went out with no seal") {
        try sender.seal(ClipOffer(id: 1, kind: 0, total: 4))
    }

    /* And a session that ends takes both halves with it. */
    let receiver = acceptingSeal()
    try sender.accepted(try receiver.accept(offer: try sender.offer()))
    let sealed = try sender.seal(ClipChunk(id: 1, seq: 0, crc32: 0, data: [1, 2, 3, 4]))
    receiver.reset()
    Check.throwsSealError(.unknownSeal, "a dropped seal still opened a payload") {
        try receiver.openChunk(sealed)
    }
}

func testStaleRoundTrips() throws {
    let sender = offeringSeal()
    let receiver = acceptingSeal()
    try sender.accepted(try receiver.accept(offer: try sender.offer()))
    let sealed = try sender.seal(ClipChunk(id: 1, seq: 0, crc32: 0, data: [1, 2, 3, 4]))

    let named = ClipboardSeal.sealID(ofMessage: MessageType.clipChunk, body: sealed)
    Check.equal(named, sealID, "the seal id could not be read from the clear head")

    let stale = ClipboardSeal.staleBody(sealID)
    Check.equal(stale, try goldenBody("seal_stale"), "the SEAL_STALE body is not the wire's")
    Check.equal(ClipboardSeal.sealID(fromStale: stale), sealID, "SEAL_STALE did not round-trip")

    Check.that(!sender.discardSeal(sealID ^ 0xFFFF_FFFF),
               "a stale for another seal discarded this one")
    Check.that(sender.canSeal, "a stale for another seal discarded this one")
    Check.that(sender.discardSeal(sealID), "the named seal was not discarded")
    Check.that(!sender.canSeal, "the named seal survived its own stale")
}

extension Check {
    /// The call must throw, and throw this seal failure.
    static func throwsSealError<T>(_ expected: SealError, _ what: String,
                                   file: StaticString = #fileID, line: UInt = #line,
                                   _ body: () throws -> T) {
        do {
            _ = try body()
            failures += 1
            print("FAIL \(file):\(line) \(what) — nothing was thrown")
        } catch {
            guard (error as? SealError) != expected else { return }
            failures += 1
            print("FAIL \(file):\(line) \(what) — threw \(error), wanted \(expected)")
        }
    }

    static func doesNotThrowSeal<T>(_ what: String, file: StaticString = #fileID,
                                    line: UInt = #line, _ body: () throws -> T) {
        do {
            _ = try body()
        } catch {
            failures += 1
            print("FAIL \(file):\(line) \(what) — threw \(error)")
        }
    }
}
