/* SPDX-License-Identifier: GPL-3.0-only */
/* Copyright (c) 2026 Derek Reynolds */

/*
 * Golden-vector tests for the core's four primitives and the frame tag (#110).
 *
 * Two vector files, one layer apart:
 *
 *   test-vectors/primitives.txt  SHA-256, HMAC, HKDF, P-256 and the session
 *                                keys, each on its own. The RFC- and
 *                                FIPS-named vectors are those documents'
 *                                published answers, so the curve and the
 *                                hashes are gated by numbers this repository
 *                                did not compute for itself.
 *   test-vectors/frames.txt      every tag on the wire, verified and then
 *                                rebuilt byte-identically from the same
 *                                published key material.
 *
 * The second one is the point. frames.txt was generated by an independent
 * Python implementation (tools/gen-frame-vectors.py); until this file existed
 * nothing checked that its tags were reproducible by the core that has to
 * produce them.
 *
 * Style follows frame_test.c: an assertion macro, a main, a printed failure
 * line, a non-zero exit — no framework.
 */

#include <ctype.h>
#include <stdio.h>
#include <string.h>

#include "dh_auth.h"
#include "dh_frame.h"
#include "dh_p256.h"
#include "dh_sha256.h"
#include "micro-ecc/uECC.h"

static int failures = 0;

#define CHECK(cond, name, what)                                                 \
    do {                                                                        \
        if (!(cond)) {                                                          \
            ++failures;                                                         \
            printf("FAIL %s:%d [%s] %s\n", __FILE__, __LINE__, (name), (what)); \
        }                                                                       \
    } while (0)

/* ------------------------------------------------------------------ loading */

#define MAX_VECTORS 64
#define MAX_FIELDS 12
#define MAX_FIELD_BYTES 512

struct vector {
    char name[64];
    size_t fields;
    uint8_t f[MAX_FIELDS][MAX_FIELD_BYTES];
    size_t len[MAX_FIELDS];
};

static int hex_nibble(int c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

/*
 * `<name> | <hex> | <hex> ...`, one vector per line, comments on '#'. Same
 * shape as frame_test.c's loader with one difference: a vector here may carry
 * several fields, and a field may be empty (the empty message, RFC 5869's
 * absent salt). frames.txt is a one-field case of the same format.
 */
static size_t load_vectors(const char *path, struct vector *out, size_t cap) {
    FILE *file = fopen(path, "r");
    if (!file) {
        ++failures;
        printf("FAIL cannot open %s\n", path);
        return 0;
    }
    char line[16384];
    size_t n = 0;
    while (fgets(line, sizeof line, file)) {
        char *p = line;
        while (*p == ' ' || *p == '\t') p++;
        if (*p == '\0' || *p == '\n' || *p == '#') continue;
        char *bar = strchr(p, '|');
        if (!bar) continue;
        if (n >= cap) { /* never silently stop gating vectors */
            ++failures;
            printf("FAIL vector capacity (%zu) exceeded in %s — raise MAX_VECTORS\n", cap, path);
            break;
        }
        struct vector *v = &out[n];
        size_t name_len = 0;
        for (char *q = p; q < bar && name_len + 1 < sizeof v->name; q++)
            if (!isspace((unsigned char)*q)) v->name[name_len++] = *q;
        v->name[name_len] = '\0';

        v->fields = 0;
        int bad = 0;
        for (char *q = bar; *q && v->fields < MAX_FIELDS; ) {
            size_t idx = v->fields++;
            v->len[idx] = 0;
            int hi = -1;
            for (q++; *q && *q != '|'; q++) {
                if (isspace((unsigned char)*q)) continue;
                int nib = hex_nibble((unsigned char)*q);
                if (nib < 0) { bad = 1; break; }
                if (hi < 0) {
                    hi = nib;
                } else {
                    if (v->len[idx] >= MAX_FIELD_BYTES) { bad = 1; break; }
                    v->f[idx][v->len[idx]++] = (uint8_t)((hi << 4) | nib);
                    hi = -1;
                }
            }
            if (bad || hi != -1) { bad = 1; break; }
            while (*q && *q != '|') q++;
        }
        if (bad) {
            ++failures;
            printf("FAIL bad hex in vector %s (%s)\n", v->name, path);
            continue;
        }
        n++;
    }
    fclose(file);
    return n;
}

static const struct vector *find(const struct vector *v, size_t n, const char *name) {
    for (size_t i = 0; i < n; i++)
        if (strcmp(v[i].name, name) == 0) return &v[i];
    ++failures;
    printf("FAIL vector %s missing\n", name);
    return NULL;
}

static int starts_with(const char *s, const char *prefix) {
    return strncmp(s, prefix, strlen(prefix)) == 0;
}

static void check_bytes(const uint8_t *got, const uint8_t *want, size_t len, const char *name,
                        const char *what) {
    if (memcmp(got, want, len) == 0) return;
    ++failures;
    printf("FAIL [%s] %s\n  got  ", name, what);
    for (size_t i = 0; i < len; i++) printf("%02x", got[i]);
    printf("\n  want ");
    for (size_t i = 0; i < len; i++) printf("%02x", want[i]);
    printf("\n");
}

/* ----------------------------------------------------------- the primitives */

static void test_primitives(const struct vector *v, size_t n) {
    /* Looked up once. find() reports a missing vector and returns NULL, so
       reaching through it inside the loop would turn a missing name into a
       crash instead of the failure line it is written to print. */
    const struct vector *helper = find(v, n, "p256_pub_helper");
    const uint8_t *a_private_key = helper ? helper->f[0] : NULL;

    size_t seen = 0;
    for (size_t i = 0; i < n; i++) {
        const struct vector *t = &v[i];
        uint8_t got[DH_SHA256_DIGEST_SIZE * 3];

        if (starts_with(t->name, "sha256_")) {
            dh_sha256(t->f[0], t->len[0], got);
            check_bytes(got, t->f[1], DH_SHA256_DIGEST_SIZE, t->name, "digest");

            /* Streamed one byte at a time, which is the only way the partial
               block and the length counter get exercised at every offset. */
            dh_sha256_ctx c;
            dh_sha256_init(&c);
            for (size_t k = 0; k < t->len[0]; k++) dh_sha256_update(&c, &t->f[0][k], 1);
            dh_sha256_final(&c, got);
            check_bytes(got, t->f[1], DH_SHA256_DIGEST_SIZE, t->name, "digest, streamed");
            seen++;

        } else if (starts_with(t->name, "hmac_")) {
            dh_hmac_sha256(t->f[0], t->len[0], t->f[1], t->len[1], got);
            check_bytes(got, t->f[2], DH_SHA256_DIGEST_SIZE, t->name, "mac");

            dh_hmac_sha256_ctx h;
            dh_hmac_sha256_init(&h, t->f[0], t->len[0]);
            for (size_t k = 0; k < t->len[1]; k++) dh_hmac_sha256_update(&h, &t->f[1][k], 1);
            dh_hmac_sha256_final(&h, got);
            check_bytes(got, t->f[2], DH_SHA256_DIGEST_SIZE, t->name, "mac, streamed");
            seen++;

        } else if (starts_with(t->name, "hkdf_")) {
            uint8_t okm[MAX_FIELD_BYTES]; /* the most a field can hold, so it fits */
            dh_hkdf_sha256(t->f[0], t->len[0], t->len[1] ? t->f[1] : NULL, t->len[1],
                           t->len[2] ? t->f[2] : NULL, t->len[2], okm, t->len[3]);
            check_bytes(okm, t->f[3], t->len[3], t->name, "okm");
            seen++;

        } else if (starts_with(t->name, "p256_pub_")) {
            uint8_t pub[DH_P256_PUBLIC_SIZE];
            CHECK(dh_p256_public_from_private(t->f[0], pub), t->name, "private key refused");
            check_bytes(pub, t->f[1], DH_P256_PUBLIC_SIZE, t->name, "public key");
            CHECK(dh_p256_public_valid(t->f[1]), t->name, "its own public key called invalid");
            seen++;

        } else if (starts_with(t->name, "p256_ecdh_")) {
            uint8_t shared[DH_P256_SHARED_SIZE];
            CHECK(dh_p256_ecdh(t->f[0], t->f[1], shared), t->name, "ecdh refused");
            check_bytes(shared, t->f[2], DH_P256_SHARED_SIZE, t->name, "shared secret");
            seen++;

        } else if (starts_with(t->name, "p256_reject_pub_")) {
            uint8_t shared[DH_P256_SHARED_SIZE];
            CHECK(!dh_p256_public_valid(t->f[0]), t->name, "accepted as a public key");
            /* And the ECDH must not be reachable around the check. */
            if (a_private_key)
                CHECK(!dh_p256_ecdh(a_private_key, t->f[0], shared), t->name,
                      "ecdh ran against an invalid peer key");
            seen++;

        } else if (starts_with(t->name, "p256_reject_priv_")) {
            uint8_t pub[DH_P256_PUBLIC_SIZE];
            CHECK(!dh_p256_public_from_private(t->f[0], pub), t->name,
                  "accepted as a private key");
            seen++;

        } else if (starts_with(t->name, "keyid_")) {
            uint8_t id[DH_KEY_ID_SIZE];
            dh_p256_key_id(t->f[0], id);
            check_bytes(id, t->f[1], DH_KEY_ID_SIZE, t->name, "key id");
            seen++;

        } else if (starts_with(t->name, "session_")) {
            seen++; /* checked in full below, where the names are known */
        }
    }
    CHECK(seen == n, "primitives.txt", "a vector was loaded that nothing dispatches on");
}

/*
 * The pairing exchange, end to end, from the two private keys alone: each
 * side computes its own public key, does one ECDH against the other's, and
 * derives the three session keys. Both sides must reach the same secret —
 * that agreement is the property pairing rests on, and a one-sided vector
 * cannot express it.
 */
static void test_session_material(const struct vector *material) {
    if (!material) return;
    const uint8_t *helper_priv = material->f[0], *board_priv = material->f[1];
    const uint8_t *helper_nonce = material->f[2], *board_nonce = material->f[3];
    const uint8_t *want_ss = material->f[4];

    uint8_t helper_pub[DH_P256_PUBLIC_SIZE], board_pub[DH_P256_PUBLIC_SIZE];
    CHECK(dh_p256_public_from_private(helper_priv, helper_pub), "session", "helper key");
    CHECK(dh_p256_public_from_private(board_priv, board_pub), "session", "board key");

    uint8_t from_helper[DH_P256_SHARED_SIZE], from_board[DH_P256_SHARED_SIZE];
    CHECK(dh_p256_ecdh(helper_priv, board_pub, from_helper), "session", "helper-side ecdh");
    CHECK(dh_p256_ecdh(board_priv, helper_pub, from_board), "session", "board-side ecdh");
    check_bytes(from_helper, want_ss, DH_P256_SHARED_SIZE, "session", "shared secret");
    check_bytes(from_board, want_ss, DH_P256_SHARED_SIZE, "session", "both sides agree");

    uint8_t k_hello[DH_SESSION_KEY_SIZE], k_h2b[DH_SESSION_KEY_SIZE], k_b2h[DH_SESSION_KEY_SIZE];
    dh_auth_derive_hello_key(from_helper, helper_nonce, k_hello);
    dh_auth_derive_session_keys(from_helper, helper_nonce, board_nonce, k_h2b, k_b2h);
    check_bytes(k_hello, material->f[5], DH_SESSION_KEY_SIZE, "session", "k_hello");
    check_bytes(k_h2b, material->f[6], DH_SESSION_KEY_SIZE, "session", "k_h2b");
    check_bytes(k_b2h, material->f[7], DH_SESSION_KEY_SIZE, "session", "k_b2h");

    /* The two directions must not share a key, or a frame could be replayed
       back at its sender. */
    CHECK(memcmp(k_h2b, k_b2h, DH_SESSION_KEY_SIZE) != 0, "session",
          "k_h2b and k_b2h are the same key");
    CHECK(memcmp(k_hello, k_h2b, DH_SESSION_KEY_SIZE) != 0, "session",
          "k_hello and k_h2b are the same key");
}

/* ------------------------------------------------------- every tag on the wire */

/*
 * For each authenticated frame in frames.txt: exactly one of the three session
 * keys must verify it, and rebuilding it under that key and its own counter
 * must reproduce the bytes. Which key goes with which frame is not hardcoded
 * here — a table of twenty-eight names would drift, and "exactly one key
 * verifies" is the stronger claim anyway.
 */
static void test_frame_tags(const struct vector *frames, size_t n,
                            const uint8_t keys[3][DH_SESSION_KEY_SIZE]) {
    size_t authenticated = 0, unauthenticated = 0;
    for (size_t i = 0; i < n; i++) {
        const struct vector *t = &frames[i];
        dh_frame_view view;
        size_t consumed = 0;
        CHECK(dh_frame_decode(t->f[0], t->len[0], &view, &consumed) == DH_FRAME_OK, t->name,
              "does not decode");
        if (consumed != t->len[0]) continue;

        if (!dh_msg_is_authenticated(view.hdr.type)) {
            unauthenticated++;
            continue;
        }
        authenticated++;

        uint64_t counter = 0;
        CHECK(dh_auth_peek_counter(view.payload, view.hdr.len, &counter), t->name,
              "no room for a prefix");

        int verified_by = -1;
        const uint8_t *body = NULL;
        size_t body_len = 0;
        for (int k = 0; k < 3; k++) {
            dh_auth_counter state;
            dh_auth_counter_init(&state);
            const uint8_t *b = NULL;
            size_t bl = 0;
            if (dh_auth_open(keys[k], &view.hdr, view.payload, &state, &b, &bl) == DH_AUTH_OK) {
                CHECK(verified_by < 0, t->name, "verifies under more than one session key");
                verified_by = k;
                body = b;
                body_len = bl;
                CHECK(state.any && state.highest == counter, t->name,
                      "counter not recorded on success");
            }
        }
        if (verified_by < 0) {
            ++failures;
            printf("FAIL [%s] no session key verifies its tag\n", t->name);
            continue;
        }

        uint8_t payload[DH_FRAME_MAX_PAYLOAD];
        size_t payload_len = 0;
        CHECK(dh_auth_wrap(keys[verified_by], view.hdr.type, view.hdr.flags, counter, body,
                           body_len, payload, sizeof payload, &payload_len) == DH_AUTH_OK,
              t->name, "will not re-wrap");
        CHECK(payload_len == view.hdr.len, t->name, "re-wrapped to a different length");
        if (payload_len == view.hdr.len)
            check_bytes(payload, view.payload, payload_len, t->name, "re-wrapped payload");
    }
    CHECK(authenticated >= 20, "frames.txt", "far fewer tagged frames than expected");
    CHECK(unauthenticated == 6, "frames.txt", "the untagged band is not the six pairing frames");
}

/* --------------------------------------------- what a bad frame must not do */

static void test_rejection(const uint8_t k_hello[DH_SESSION_KEY_SIZE],
                           const struct vector *hello) {
    if (!hello) return;

    dh_frame_view view;
    size_t consumed = 0;
    if (dh_frame_decode(hello->f[0], hello->len[0], &view, &consumed) != DH_FRAME_OK) return;

    const uint8_t *body = NULL;
    size_t body_len = 0;
    dh_auth_counter state;

    /* A body byte changed: the tag covers it. */
    uint8_t tampered[MAX_FIELD_BYTES]; /* bounded by the loader, not by today's hello */
    memcpy(tampered, view.payload, view.hdr.len);
    tampered[DH_FRAME_AUTH_PREFIX_SIZE] ^= 1u;
    dh_auth_counter_init(&state);
    CHECK(dh_auth_open(k_hello, &view.hdr, tampered, &state, &body, &body_len) == DH_AUTH_ERR_TAG,
          "hello_mac", "a changed body still verifies");
    CHECK(!state.any, "hello_mac", "a failed tag moved the counter");

    /* The type byte changed: binding it is what stops one message being read
       as another under the same tag. */
    dh_frame_header retyped = view.hdr;
    retyped.type = DH_MSG_PLACE;
    dh_auth_counter_init(&state);
    CHECK(dh_auth_open(k_hello, &retyped, view.payload, &state, &body, &body_len)
              == DH_AUTH_ERR_TAG,
          "hello_mac", "re-typing the frame keeps its tag");

    /* The length changed: binding it is what stops a truncation. */
    dh_frame_header shortened = view.hdr;
    shortened.len = (uint16_t)(view.hdr.len - 1u);
    dh_auth_counter_init(&state);
    CHECK(dh_auth_open(k_hello, &shortened, view.payload, &state, &body, &body_len)
              == DH_AUTH_ERR_TAG,
          "hello_mac", "truncating the frame keeps its tag");

    /* A payload with no room for a prefix is short, not forged. */
    dh_frame_header stub = view.hdr;
    stub.len = (uint16_t)(DH_FRAME_AUTH_PREFIX_SIZE - 1u);
    dh_auth_counter_init(&state);
    CHECK(dh_auth_open(k_hello, &stub, view.payload, &state, &body, &body_len)
              == DH_AUTH_ERR_SHORT,
          "hello_mac", "a truncated prefix is not reported as short");

    /* The good frame, twice: the second is a replay and the counter refuses it. */
    dh_auth_counter_init(&state);
    CHECK(dh_auth_open(k_hello, &view.hdr, view.payload, &state, &body, &body_len) == DH_AUTH_OK,
          "hello_mac", "the real frame does not verify");
    CHECK(dh_auth_open(k_hello, &view.hdr, view.payload, &state, &body, &body_len)
              == DH_AUTH_ERR_COUNTER,
          "hello_mac", "a replay is accepted");
}

/* The counter is readable from 8 payload bytes, which is what makes
   docs/protocol.md's "reject a replay after reading 12 bytes" possible. */
static void test_peek_needs_only_the_counter(void) {
    const uint8_t prefix[DH_FRAME_COUNTER_SIZE] = {7, 0, 0, 0, 0, 0, 0, 0};
    uint64_t counter = 0;
    CHECK(dh_auth_peek_counter(prefix, sizeof prefix, &counter), "peek",
          "8 bytes is not enough to read the counter");
    CHECK(counter == 7, "peek", "wrong counter read");
    CHECK(!dh_auth_peek_counter(prefix, sizeof prefix - 1u, &counter), "peek",
          "read a counter out of 7 bytes");
}

/* Past 255 expand blocks the one-byte counter would wrap and the output would
   stop being HKDF. Writing nothing is the defined answer. */
static void test_hkdf_output_limit(void) {
    uint8_t out[64];
    memset(out, 0xA5, sizeof out);
    dh_hkdf_sha256((const uint8_t *)"k", 1, NULL, 0, NULL, 0, out, DH_HKDF_MAX_OUTPUT + 1u);
    for (size_t i = 0; i < sizeof out; i++)
        CHECK(out[i] == 0xA5, "hkdf", "an over-long request wrote something");
}

static void test_counter(void) {
    dh_auth_counter c;
    dh_auth_counter_init(&c);

    /* Counter 0 is a real counter — the hello uses it — so an "unset" state
       cannot be represented by a zero. */
    CHECK(dh_auth_counter_ok(&c, 0), "counter", "0 refused on a fresh key");
    dh_auth_counter_accept(&c, 0);
    CHECK(!dh_auth_counter_ok(&c, 0), "counter", "0 accepted twice");
    CHECK(dh_auth_counter_ok(&c, 1), "counter", "1 refused after 0");

    /* Gaps are ordinary: the device's outbound queue is bounded and a frame it
       cannot take is a silent loss (ADR-0005). */
    dh_auth_counter_accept(&c, 5);
    CHECK(dh_auth_counter_ok(&c, 9), "counter", "a gap refused");
    CHECK(!dh_auth_counter_ok(&c, 5), "counter", "a repeat accepted");
    CHECK(dh_auth_counter_ok(&c, UINT64_MAX), "counter", "the top of the space refused");

    /*
     * Arriving late is not arriving twice, and this is the whole of the
     * distinction. The board tags a frame when it is built and its outbound
     * queue then reorders — a priority frame overtakes bulk that is merely
     * queued (ADR-0005) — so 4 behind 5 is an ordinary event on this path and
     * refusing it is what stalled every clipboard transfer on the first
     * hardware run of #52.
     */
    CHECK(dh_auth_counter_ok(&c, 4), "counter", "a reordered frame was refused");
    dh_auth_counter_accept(&c, 4);
    CHECK(!dh_auth_counter_ok(&c, 4), "counter", "a reordered frame was accepted twice");
    /* Its neighbours are untouched by it. */
    CHECK(dh_auth_counter_ok(&c, 3), "counter", "accepting 4 refused 3");
    CHECK(!dh_auth_counter_ok(&c, 5), "counter", "accepting 4 forgot 5");
}

/*
 * What the far end tagged against what got here. The board→helper direction
 * had no counter of any kind until #143, which is why a desynchronised reader
 * took a failed tag to notice; the counter state already held both halves of
 * the answer and nothing asked it.
 */
static void test_counter_missed(void) {
    dh_auth_counter c;
    dh_auth_counter_init(&c);
    CHECK(dh_auth_counter_missed(&c) == 0, "missed", "a fresh key has already lost something");

    /* The hello is 0, and a session that has only had its hello has lost
       nothing. */
    dh_auth_counter_accept(&c, 0);
    CHECK(dh_auth_counter_missed(&c) == 0, "missed", "the first counter reads as a loss");

    dh_auth_counter_accept(&c, 1);
    dh_auth_counter_accept(&c, 2);
    CHECK(dh_auth_counter_missed(&c) == 0, "missed", "a consecutive run reads as a loss");

    /* 3 and 4 never arrived. */
    dh_auth_counter_accept(&c, 5);
    CHECK(dh_auth_counter_missed(&c) == 2, "missed", "a gap of two was not counted as two");

    /* One of them was merely late, not lost — the reorder ADR-0005 permits.
       Arriving closes the gap rather than widening it. */
    dh_auth_counter_accept(&c, 4);
    CHECK(dh_auth_counter_missed(&c) == 1, "missed", "a late frame did not close its own gap");

    /* A replay is refused before it is recorded, so it cannot flatter this
       number. dh_auth_open asks first; asking here is the same contract. */
    if (!dh_auth_counter_ok(&c, 4)) {
        CHECK(dh_auth_counter_missed(&c) == 1, "missed", "a replay moved the reading");
    } else {
        CHECK(0, "missed", "a replay was not refused");
    }
}

/* A frame that fails its tag never reaches the counter, so it is not a loss
   this reading may claim: dh_auth_open verifies before it records. */
static void test_missed_ignores_a_failed_tag(const uint8_t key[DH_SESSION_KEY_SIZE]) {
    uint8_t frame[128];
    size_t len = 0;
    const uint8_t body[4] = {9, 9, 9, 9};
    CHECK(dh_auth_frame(DH_MSG_PLACE, 0, key, 0, body, sizeof body, frame, sizeof frame, &len)
              == DH_FRAME_OK,
          "missed", "the frame would not build");

    dh_auth_counter c;
    dh_auth_counter_init(&c);

    dh_frame_header hdr;
    CHECK(dh_frame_header_parse(frame, len, &hdr) == DH_FRAME_OK, "missed",
          "the frame would not parse");

    const uint8_t *out_body = NULL;
    size_t out_len = 0;
    CHECK(dh_auth_open(key, &hdr, frame + DH_FRAME_HEADER_SIZE, &c, &out_body, &out_len)
              == DH_AUTH_OK,
          "missed", "a good frame would not open");
    CHECK(dh_auth_counter_missed(&c) == 0, "missed", "an accepted frame reads as a loss");

    /* The same frame with one tag byte turned over. */
    frame[DH_FRAME_HEADER_SIZE + DH_FRAME_COUNTER_SIZE] ^= 0x01u;
    CHECK(dh_auth_open(key, &hdr, frame + DH_FRAME_HEADER_SIZE, &c, &out_body, &out_len)
              == DH_AUTH_ERR_TAG,
          "missed", "a broken tag was accepted");
    CHECK(dh_auth_counter_missed(&c) == 0, "missed", "a failed tag moved the reading");
}

/*
 * The window's two edges. Both are refusals, and they refuse for different
 * reasons: one because the counter has been through, one because the record of
 * whether it has no longer exists. Accepting on an absence of evidence is
 * exactly what a replay window exists to prevent.
 */
static void test_counter_window_edges(void) {
    dh_auth_counter c;
    dh_auth_counter_init(&c);
    dh_auth_counter_accept(&c, 1000);

    CHECK(dh_auth_counter_ok(&c, 1000 - (DH_AUTH_WINDOW - 1)), "window",
          "the oldest counter still inside the window was refused");
    CHECK(!dh_auth_counter_ok(&c, 1000 - DH_AUTH_WINDOW), "window",
          "a counter past the window was accepted");
    CHECK(!dh_auth_counter_ok(&c, 0), "window", "a counter far past the window was accepted");

    /* A jump wider than the window clears the record rather than carrying bits
       that no longer mean anything — and the new highest is itself seen. */
    dh_auth_counter_accept(&c, 1000 + DH_AUTH_WINDOW + 5);
    CHECK(!dh_auth_counter_ok(&c, 1000 + DH_AUTH_WINDOW + 5), "window",
          "the counter that made the jump was accepted again");
    CHECK(!dh_auth_counter_ok(&c, 1000), "window",
          "a counter the jump left behind was accepted");

    /* Every counter in one full window, delivered backwards, is accepted once
       and only once — the strongest statement of "late is not twice". */
    dh_auth_counter fresh;
    dh_auth_counter_init(&fresh);
    dh_auth_counter_accept(&fresh, DH_AUTH_WINDOW);
    for (uint64_t n = DH_AUTH_WINDOW - 1; n > 0; n--) {
        CHECK(dh_auth_counter_ok(&fresh, n), "window", "a counter in the window was refused");
        dh_auth_counter_accept(&fresh, n);
        CHECK(!dh_auth_counter_ok(&fresh, n), "window", "a counter was accepted twice");
    }
}

static void test_wrap_buffer(const uint8_t key[DH_SESSION_KEY_SIZE]) {
    uint8_t out[64];
    size_t out_len = 0;
    const uint8_t body[4] = {1, 2, 3, 4};

    CHECK(dh_auth_wrap(key, DH_MSG_PLACE, 0, 7, body, sizeof body, out, sizeof out, &out_len)
              == DH_AUTH_OK,
          "wrap", "a small frame will not wrap");
    CHECK(out_len == DH_FRAME_AUTH_PREFIX_SIZE + sizeof body, "wrap", "wrong wrapped length");

    /* One byte short, rather than one byte over: dh_frame_encode returns
       DH_FRAME_ERR_BUFFER rather than truncating, and this must match it. */
    CHECK(dh_auth_wrap(key, DH_MSG_PLACE, 0, 7, body, sizeof body, out, out_len - 1, &out_len)
              == DH_AUTH_ERR_BUFFER,
          "wrap", "a short buffer was written anyway");

    /* An empty body is the heartbeat, and it is prefix and nothing else. */
    CHECK(dh_auth_wrap(key, DH_MSG_HEARTBEAT, 0, 0, NULL, 0, out, sizeof out, &out_len)
              == DH_AUTH_OK,
          "wrap", "an empty body will not wrap");
    CHECK(out_len == DH_FRAME_AUTH_PREFIX_SIZE, "wrap", "an empty body is not just a prefix");
}

static void test_constant_time_compare(void) {
    const uint8_t a[4] = {1, 2, 3, 4};
    const uint8_t b[4] = {1, 2, 3, 5};
    CHECK(dh_auth_bytes_equal(a, a, sizeof a), "compare", "equal buffers differ");
    CHECK(!dh_auth_bytes_equal(a, b, sizeof a), "compare", "different buffers match");
    CHECK(dh_auth_bytes_equal(a, b, 3), "compare", "a shared prefix does not match");
    CHECK(dh_auth_bytes_equal(a, b, 0), "compare", "zero length is not equal");
}

/*
 * micro-ecc installs a default RNG on any host platform — it opens
 * /dev/urandom (platform-specific.inc). This core has no entropy source and
 * does no I/O, so dh_p256.c clears that pointer. Nothing else would notice if
 * that stopped happening: the results would be identical and the file
 * descriptor invisible.
 */
static void test_no_entropy_source(void) {
    /* Before any call into dh_p256, which would clear the pointer itself and
       make this pass whether or not a default was ever linked in. Ordered
       this way, it is the null-at-start-up claim being tested. */
    CHECK(uECC_get_rng() == NULL, "entropy", "micro-ecc linked in a default RNG");

    uint8_t pub[DH_P256_PUBLIC_SIZE];
    uint8_t priv[DH_P256_PRIVATE_SIZE];
    memset(priv, 0x11, sizeof priv);
    dh_p256_public_from_private(priv, pub);
    CHECK(uECC_get_rng() == NULL, "entropy", "a dh_p256 call left an RNG installed");
}

int main(int argc, char **argv) {
    const char *primitives_path = argc > 1 ? argv[1] : DH_PRIMITIVE_VECTORS;
    const char *frames_path = argc > 2 ? argv[2] : DH_TEST_VECTORS;

    static struct vector primitives[MAX_VECTORS];
    static struct vector frames[MAX_VECTORS];
    size_t np = load_vectors(primitives_path, primitives, MAX_VECTORS);
    size_t nf = load_vectors(frames_path, frames, MAX_VECTORS);
    CHECK(np > 30, primitives_path, "far fewer primitive vectors than expected");
    CHECK(nf > 20, frames_path, "far fewer frame vectors than expected");

    test_no_entropy_source(); /* first: any dh_p256 call would clear the pointer */
    test_primitives(primitives, np);

    const struct vector *material = find(primitives, np, "session_material");
    test_session_material(material);

    if (material) {
        uint8_t keys[3][DH_SESSION_KEY_SIZE];
        memcpy(keys[0], material->f[5], DH_SESSION_KEY_SIZE); /* k_hello */
        memcpy(keys[1], material->f[6], DH_SESSION_KEY_SIZE); /* k_h2b   */
        memcpy(keys[2], material->f[7], DH_SESSION_KEY_SIZE); /* k_b2h   */
        test_frame_tags(frames, nf, (const uint8_t (*)[DH_SESSION_KEY_SIZE])keys);
        test_rejection(keys[0], find(frames, nf, "hello_mac"));
        test_wrap_buffer(keys[1]);
        test_missed_ignores_a_failed_tag(keys[1]);
    }

    test_counter();
    test_counter_missed();
    test_counter_window_edges();
    test_peek_needs_only_the_counter();
    test_hkdf_output_limit();
    test_constant_time_compare();

    if (failures) {
        printf("%d failure(s)\n", failures);
        return 1;
    }
    printf("auth_test ok (%zu primitive vectors, %zu frames)\n", np, nf);
    return 0;
}
