/* SPDX-License-Identifier: GPL-3.0-only */
/* Copyright (c) 2026 Derek Reynolds */

/*
 * The seal, from this helper's side (#113).
 *
 * What this gates is the one thing neither the C suite nor the macOS suite
 * can: **CNG's** AES-256-GCM producing the same bytes as everyone else's. The
 * golden vectors were generated by an independent Python implementation,
 * `tests/seal_test.c` reproduces them with the C suite's reference cipher, the
 * macOS suite reproduces them through CryptoKit, and this reproduces them
 * through the cipher this helper ships. Four implementations agreeing on the
 * published bytes is what says a payload sealed on one computer opens on the
 * other.
 *
 * Windows only, because BCrypt is. The key material is the fixed, published,
 * obviously fake material tools/gen-frame-vectors.py uses.
 *
 * Style follows autostart_ladder_test.cpp — an assertion macro, a main, a
 * printed failure line, a non-zero exit. No framework (ADR-0006).
 */

#include <cctype>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "dh_frame.h"
#include "dh_seal.h"
#include "seal_aead.h"

static int failures = 0;

#define CHECK(cond, what)                                               \
    do {                                                                \
        if (!(cond)) {                                                  \
            ++failures;                                                 \
            std::printf("FAIL %s:%d %s\n", __FILE__, __LINE__, (what)); \
        }                                                               \
    } while (0)

/* ------------------------------------------------------------ the vectors */

/* `<name> | <hex bytes>`, one per line, comments on '#'. */
static std::vector<uint8_t> golden_frame(const char *name) {
    std::FILE *file = std::fopen(DH_TEST_VECTORS, "r");
    if (!file) {
        ++failures;
        std::printf("FAIL cannot open %s\n", DH_TEST_VECTORS);
        return {};
    }

    std::vector<uint8_t> bytes;
    char line[16384];
    while (std::fgets(line, sizeof line, file)) {
        if (line[0] == '#' || line[0] == '\n') continue;
        const char *bar = std::strchr(line, '|');
        if (!bar) continue;

        std::string found;
        for (const char *p = line; p < bar; p++)
            if (!std::isspace(static_cast<unsigned char>(*p))) found.push_back(*p);
        if (found != name) continue;

        int hi = -1;
        for (const char *p = bar + 1; *p; p++) {
            const char c = *p;
            int nibble;
            if (c >= '0' && c <= '9') nibble = c - '0';
            else if (c >= 'a' && c <= 'f') nibble = c - 'a' + 10;
            else if (c >= 'A' && c <= 'F') nibble = c - 'A' + 10;
            else continue;
            if (hi < 0) {
                hi = nibble;
            } else {
                bytes.push_back(static_cast<uint8_t>((hi << 4) | nibble));
                hi = -1;
            }
        }
        break;
    }
    std::fclose(file);

    if (bytes.size() < DH_FRAME_HEADER_SIZE + DH_FRAME_AUTH_PREFIX_SIZE) {
        ++failures;
        std::printf("FAIL vector %s missing or too short\n", name);
        return {};
    }
    /* The body alone: the header and the hop's tag belong to neither end of
       the seal. */
    return std::vector<uint8_t>(bytes.begin() + DH_FRAME_HEADER_SIZE + DH_FRAME_AUTH_PREFIX_SIZE,
                                bytes.end());
}

static void check_bytes(const std::vector<uint8_t> &got, const std::vector<uint8_t> &want,
                        const char *what) {
    if (got == want) return;
    ++failures;
    std::printf("FAIL %s\n  got  ", what);
    for (uint8_t b : got) std::printf("%02x", b);
    std::printf("\n  want ");
    for (uint8_t b : want) std::printf("%02x", b);
    std::printf("\n");
}

/* ----------------------------------------------------------- the material */

static const uint32_t SEAL_ID = 0x11223344u;

static std::vector<uint8_t> ramp(uint8_t first, size_t count) {
    std::vector<uint8_t> bytes(count);
    for (size_t i = 0; i < count; i++) bytes[i] = static_cast<uint8_t>(first + i);
    return bytes;
}

/* The two ends of one seal, established the way two helpers establish one. */
static void a_live_seal(dh_seal_tx *tx, dh_seal_rx *rx) {
    const std::vector<uint8_t> offer_private = ramp(0x41, DH_P256_PRIVATE_SIZE);
    const std::vector<uint8_t> accept_private = ramp(0x61, DH_P256_PRIVATE_SIZE);
    const std::vector<uint8_t> offer_nonce = ramp(0x20, DH_NONCE_SIZE);
    const std::vector<uint8_t> accept_nonce = ramp(0x30, DH_NONCE_SIZE);

    dh_seal_tx_init(tx);
    dh_seal_rx_init(rx);

    uint8_t offer[DH_SEAL_EXCHANGE_LEN], accept[DH_SEAL_EXCHANGE_LEN];
    size_t offer_len = 0, accept_len = 0;
    CHECK(dh_seal_tx_offer(tx, SEAL_ID, offer_private.data(), offer_nonce.data(), offer,
                           sizeof offer, &offer_len) == DH_SEAL_OK,
          "the offer was not built");
    CHECK(dh_seal_rx_offered(rx, offer, offer_len, accept_private.data(), accept_nonce.data(),
                             accept, sizeof accept, &accept_len) == DH_SEAL_OK,
          "the offer was not accepted");
    CHECK(dh_seal_tx_accepted(tx, accept, accept_len) == DH_SEAL_OK, "the accept was refused");

    check_bytes(std::vector<uint8_t>(offer, offer + offer_len), golden_frame("seal_offer"),
                "the SEAL_OFFER body is not the wire's");
    check_bytes(std::vector<uint8_t>(accept, accept + accept_len), golden_frame("seal_accept"),
                "the SEAL_ACCEPT body is not the wire's");
}

/* ------------------------------------------------------------- the checks */

/*
 * The two messages that carry the user's bytes, sealed by CNG and compared
 * with what Python produced. They come off one key in this order, so the offer
 * spends counter 0 and the chunk counter 1.
 */
static void sealed_payloads_match_the_wire() {
    const dh_seal_aead *aead = deskhop::seal_aead();
    CHECK(aead != nullptr, "CNG would not provide AES-GCM");
    if (!aead) return;

    dh_seal_tx tx;
    dh_seal_rx rx;
    a_live_seal(&tx, &rx);

    uint8_t body[DH_FRAME_MAX_PAYLOAD];
    size_t len = 0;

    dh_clip_offer offer = {};
    offer.id = 1;
    offer.kind = 0;
    offer.total = 2;
    CHECK(dh_seal_encode_offer(&tx, aead, &offer, body, sizeof body, &len) == DH_SEAL_OK,
          "the offer was not sealed");
    check_bytes(std::vector<uint8_t>(body, body + len), golden_frame("clip_offer_text2"),
                "the sealed CLIP_OFFER is not the wire's");

    uint8_t plain[DH_FRAME_MAX_PAYLOAD];
    dh_clip_offer read_offer = {};
    CHECK(dh_seal_open_offer(&rx, aead, body, len, plain, sizeof plain, &read_offer) ==
              DH_SEAL_OK,
          "the offer did not open");
    CHECK(read_offer.id == 1 && read_offer.kind == 0 && read_offer.total == 2,
          "the offer opened to something else");

    const uint8_t hi[2] = {'h', 'i'};
    dh_clip_chunk chunk = {};
    chunk.id = 2;
    chunk.seq = 0;
    chunk.crc32 = 0xd8932aacu; /* CRC32("hi"), as the golden vector carries it */
    chunk.data = hi;
    chunk.data_len = 2;
    CHECK(dh_seal_encode_chunk(&tx, aead, &chunk, body, sizeof body, &len) == DH_SEAL_OK,
          "the chunk was not sealed");
    check_bytes(std::vector<uint8_t>(body, body + len), golden_frame("clip_chunk_hi"),
                "the sealed CLIP_CHUNK is not the wire's");

    dh_clip_chunk read_chunk = {};
    CHECK(dh_seal_open_chunk(&rx, aead, body, len, plain, sizeof plain, &read_chunk) ==
              DH_SEAL_OK,
          "the chunk did not open");
    CHECK(read_chunk.id == 2 && read_chunk.seq == 0 && read_chunk.data_len == 2 &&
              std::memcmp(read_chunk.data, hi, 2) == 0,
          "the chunk opened to something else");
}

/* The clear head is the AAD, so a board that edited an id, a sequence number
   or a counter in flight would produce a frame that no longer opens. */
static void an_edited_head_does_not_open() {
    const dh_seal_aead *aead = deskhop::seal_aead();
    if (!aead) return;

    dh_seal_tx tx;
    dh_seal_rx rx;
    a_live_seal(&tx, &rx);

    const uint8_t data[4] = {1, 2, 3, 4};
    dh_clip_chunk chunk = {};
    chunk.id = 9;
    chunk.seq = 3;
    chunk.crc32 = 0;
    chunk.data = data;
    chunk.data_len = 4;

    uint8_t body[DH_FRAME_MAX_PAYLOAD], plain[DH_FRAME_MAX_PAYLOAD];
    size_t len = 0;
    CHECK(dh_seal_encode_chunk(&tx, aead, &chunk, body, sizeof body, &len) == DH_SEAL_OK,
          "the chunk was not sealed");

    dh_clip_chunk read = {};
    const size_t offsets[] = {0, 4, 12, len - 1};
    for (size_t offset : offsets) {
        body[offset] ^= 0x01u;
        CHECK(dh_seal_open_chunk(&rx, aead, body, len, plain, sizeof plain, &read) ==
                  DH_SEAL_ERR_AUTH,
              "an edited frame still opened");
        body[offset] ^= 0x01u;
    }
    CHECK(dh_seal_open_chunk(&rx, aead, body, len, plain, sizeof plain, &read) == DH_SEAL_OK,
          "the unedited frame stopped opening");
}

/* There is no unsealed path and no build that turns the seal off: #44's
   exemption is the board's, and the board is not a party to this key. */
static void nothing_goes_out_unsealed() {
    const dh_seal_aead *aead = deskhop::seal_aead();
    if (!aead) return;

    dh_seal_tx tx;
    dh_seal_tx_init(&tx);

    const uint8_t data[4] = {1, 2, 3, 4};
    dh_clip_chunk chunk = {};
    chunk.id = 1;
    chunk.data = data;
    chunk.data_len = 4;

    uint8_t body[DH_FRAME_MAX_PAYLOAD];
    size_t len = 0;
    CHECK(dh_seal_encode_chunk(&tx, aead, &chunk, body, sizeof body, &len) ==
              DH_SEAL_ERR_NO_SEAL,
          "a chunk was sealed with no seal");
    CHECK(len == 0, "a refused encode reported a length");
}

int main() {
    sealed_payloads_match_the_wire();
    an_edited_head_does_not_open();
    nothing_goes_out_unsealed();

    if (failures == 0) std::printf("seal_test: all checks passed\n");
    return failures == 0 ? 0 : 1;
}
